SET NEWPAGE none
SET FEEDBACK OFF
set head off;
-- select CONCAT('The Hostname is: ', host_name) from v$instance;
-- select CONCAT('Host cpu_count is: ', (SELECT value from v$parameter where name='cpu_count')) from dual;
-- select CONCAT('Physical Memory size is: ', (SELECT max(value)/1024/1024/1024 from dba_hist_osstat where stat_name = 'PHYSICAL_MEMORY_BYTES')) from dual;
select CONCAT('The DB version is: ', version_full) from PRODUCT_COMPONENT_VERSION;
select CONCAT('The DB edition is: ', PRODUCT) from PRODUCT_COMPONENT_VERSION;
select CONCAT('dNFS enabled: ', (select decode(count(*), 0, 'No', 'Yes') from v$dnfs_servers)) from dual;
select CONCAT('The DB instance is: ', instance_name) from v$instance;
select CONCAT('The DB ID is: ', dbid) from v$database;
select CONCAT('The DB Name is: ', name) from v$database;
select CONCAT('The DB Unique name is: ', db_unique_name) from v$database;
select CONCAT('The DB Platform name is: ', platform_name) from v$database;
select CONCAT('The DB log mode is: ', log_mode) from v$database;
select CONCAT('The DB flashback is: ', flashback_on) from v$database;
-- select CONCAT('The con_id: ', con_id) from v$containers;
-- select CONCAT('The con_name: ', name) from v$containers;
select CONCAT('Is this CDB/Multitenant?: ', (select decode(count(*), 0, 'NO', 'YES') con_id from v$containers where con_id != 0)) from dual;
select CONCAT('The Number of PDBs: ', (select count(pdb_name) from DBA_PDBS where pdb_name != 'PDB$SEED')) from dual;
select CONCAT('The DB status is: ', status) from v$instance;
select CONCAT('The DB size based on segments in GiB: ', (select sum(bytes)/1024/1024/1024 from dba_segments)) from dual;
select CONCAT('The Total bigfile Datasize in GiB: ', (select sum(bytes)/1024/1024/1024 from (select sum(bytes) bytes from dba_data_files dbf, dba_tablespaces tbsp where dbf.tablespace_name=tbsp.tablespace_name and tbsp.bigfile='YES'))) from dual;
select CONCAT('The Biggest bigfile in GiB: ', (select sum(bytes/1024/1024/1024) from (select max(bytes) bytes from dba_data_files dbf, dba_tablespaces tbsp where dbf.tablespace_name=tbsp.tablespace_name and tbsp.bigfile='YES'))) from dual;
select CONCAT('The allocated DB size based on datafile in GiB: ', (select sum(bytes)/1024/1024/1024 BYTES from v$datafile)) from dual;
select CONCAT('The total datafiles in the DB is: ', (select count(*) from v$datafile)) from dual;
select CONCAT('The total tablespaces in the DB is: ', (select count(*) from v$tablespace)) from dual;
select CONCAT('Bigfile tablespace count: ', (select count(*) from dba_tablespaces where bigfile='YES')) from dual;
select CONCAT('Bigfile Data size in MiB: ', (select sum(bytes/1024/1024) from (select max(bytes) bytes from v$datafile dbf, v$tablespace tbsp where dbf.TS#=tbsp.TS# and tbsp.bigfile='YES'))) from dual;
select CONCAT('TEMP datafile count is: ', (select count(*) from v$tempfile)) from dual;
select CONCAT('The daily redo size in MiB is: ', (select dailyRedoSize from (select avg(redo_size/1024/1024) dailyRedoSize from (select trunc(completion_time) rundate, sum(blocks*block_size) redo_size from v$archived_log where first_time > sysdate - 7 group by trunc(completion_time))))) from dual;
select CONCAT('The daily change rate is: ', (select dailyChangeRate from (select round((avg(redo_size)/sum(sgmt.bytes)),8) dailyChangeRate from containers(cdb_segments) sgmt, (select trunc(completion_time) rundate, sum(blocks*block_size) redo_size from containers(v$archived_log) where first_time > sysdate - 7 group by trunc(completion_time))))) from dual;
select CONCAT('The DB Block size in bytes: ', (select value from v$parameter where name='db_block_size')) from dual;
select CONCAT('The DB spfile is present: ', (select decode(count(*), 0, 'NO', 'YES') from v$parameter where name='spfile')) from dual;
select CONCAT('Patchlevel is: ', (select * from (select description from dba_registry_sqlpatch order by ACTION_TIME desc) where ROWNUM = 1)) from dual;
select CONCAT('Is it Cluster: ', (SELECT value from v$parameter where name='cluster_database')) from dual;
select CONCAT('Cluster DB Instances: ', (SELECT value from v$parameter where name='cluster_database_instances')) from dual;
select CONCAT('SGA MAX SIze: ', (SELECT value/1024/1024/1024 from v$parameter where name='sga_max_size')) from dual;
select CONCAT('SGA Target size in GiB: ', (SELECT value/1024/1024/1024 from v$parameter where name='sga_target')) from dual;
select CONCAT('PGA Target size in GiB: ', (SELECT value/1024/1024/1024 from v$parameter where name='pga_aggregate_target')) from dual;
select CONCAT('Is it GoldenGate config: ', (select decode(count(*), 0, 'NO', 'YES') from v$archive_dest where status = 'VALID' and target = 'STANDBY')) from dual;
select CONCAT('Is it Exadata enabled: ', (select decode(count(*), 0, 'NO', 'YES') from v$cell)) from dual;
select CONCAT('Is Block Change Tracking enabled: ', (select status from v$block_change_tracking)) from dual;
select CONCAT('Archive Log Config: ', (SELECT value from v$parameter where name='log_archive_config')) from dual;
select CONCAT('Archive Lag Target: ', (SELECT value from v$parameter where name='archive_lag_target')) from dual;
select CONCAT('Total tablespace count: ', (select count(*)  from v$tablespace)) from dual;
select CONCAT('Encrypted tablespace count: ', (select count(*) from dba_tablespaces dba, v$tablespace v where dba.encrypted='YES' and dba.tablespace_name=v.name)) from dual;
select CONCAT('Encrypted Datasize in MiB: ', (select sum(bytes/1024/1024) from (select sum(bytes) bytes from v$datafile dbf, v$tablespace v, dba_tablespaces tbsp where dbf.TS#=v.TS# and v.name=tbsp.tablespace_name and tbsp.encrypted='YES'))) from dual;
select CONCAT('FRA configured: ', (select value from v$parameter where name='db_recovery_file_dest')) from dual;
select CONCAT('FRA size in GiB: ', (select value/1024/1024/1024 from v$parameter where name='db_recovery_file_dest_size')) from dual;
select CONCAT('Are datafiles on ASM: ', (select decode(count(*), 0, 'No', 'Yes') name from v$datafile where name like '+%')) from dual;
select CONCAT('Are archive log files on ASM: ', (select decode(count(*), 0, 'No', 'Yes') name from v$archived_log where name like '+%')) from dual;
select CONCAT('Are REDO log files on ASM: ', (select decode(count(*), 0, 'No', 'Yes') member from v$logfile where member like '+%')) from dual;
select CONCAT('Is Control file on ASM: ', (select decode(count(*), 0, 'No', 'Yes') name from v$datafile where name like '+%')) from dual;
quit
